spring.application.name=Edhukan UserService
security.jwt.secret=wRkRkLfK7jinNe6QicV5RiSC9bt0iCEPQTwe45g78r/oWV1+QvRQXS6/QIDekuAsZwQN1j3zfRjLJHvgbva5UJbF/+tW3/tPfgvo4tMr4mi3BljKd6AlwKdbNExFObithNGR9DC/oKvXHLIQMtWZPZi3+HHG/QvsgZhW/gCJSFwyCpWs3MpbZe04TkCMqOAhCxQi1a6O0mA0BtWsFq6u8os6ufJST7YLMZOwh4p/hy01ICqw2rWgAVLMPpQZ7UvSk3OLYunb+cq3/yxx3b3kjJKFP0apRJ2kjjyEQTPIkg6R507e1WaOX4vNB2D+EQJV6ZSt5Ko4iaPgxxtS/uxOZQ==
app.jwtExpirationMs=86400000
#TRACE all Logs when we click any EndPoint
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

#app.jwtSecret=6ScmGiQkuY0rJDGJfs3fdw47TptbRXA+T2+ltlL9Rr66OzyRk1QqC7axCmw2zI2FRsnlHjxddFxlvzPq4DqQaFs6Csv+pD/1iX7OKwLAQa7ySbCcG7BuhmZw7N6EhP7tgiY9QGFV9spwyHEfIgGQyn8Sin1/SMgkIQ6pKSFUktI5eqKbbnqPOZKiMSIIfwIqPlySHd5gY7K0qlZP8LWG3DkkS5IytEiHJedILF7c779Jtg21zqDdRhyu96TWDUuNSjxWkvtqyL6mSpwvP8l/DIT+s0mOppn3nWlSjpUNZFTd6ne6x1qwj/opMLJ/jbbMbindqM2FI06YHXYI35h2Hg==
app.jwtIssuer = http://localhost:8081
#Connection for DataBase
spring.jpa.hibernate.ddl-auto=validate
#spring.datasource.url=jdbc:postgresql://userservicedbmaster.c1akoai2882y.us-east-2.rds.amazonaws.com:5432/userservicedbmaster
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/userservicedbmaster
spring.datasource.username=masteruser
#spring.datasource.password=password2001
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
#Displays all the SQL Queries being run!
spring.jpa.show-sql=true

server.port=8081
#SSL Certificate
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=password
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=my-ssl-key

logging.level.org.springframework.security.oauth2.server.authorization=DEBUG
#Spring Security Authorization Properties
#logging.level.org.springframework.security= trace
#spring.security.user.name= user
#spring.security.user.password= password
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-id= "oidc-client"
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-secret= "{noop}secret"
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-authentication-methods[0]= "client_secret_basic"  // Array index for the first method
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.authorization-grant-types[0]= "authorization_code"
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.authorization-grant-types[1]= "refresh_token"
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.redirect-uris[0]= "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.post-logout-redirect-uris[0]= "http://127.0.0.1:8080/"
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.scopes[0]= "openid"
#spring.security.oauth2.authorizationserver.client.oidc-client.registration.scopes[1]= "profile"
#spring.security.oauth2.authorizationserver.client.oidc-client.require-authorization-consent= true

logging.level.org.springframework=DEBUG